### ISSUE TITLE
Score issue

### ISSUE THREAD

**Issue by Kyrony** [JohnnyOhms/Javascript-QuizApp#1]
![image](https://user-images.githubusercontent.com/88354135/183258038-6efa38e1-708e-4c94-8ac7-c09fcf419788.png)

in the quiz.js file, there's nothing stopping you from clicking the correct answer over and over again! Allowing me to score well above 10. Adding a class that sets the z-index to the back would prevent this from happening and would only allow you to pick one answer!

**Comment by JohnnyOhms** [comment]
Thanks for you contribution, sorry it took long before I had to reply 🙂

**Comment by Kyrony** [comment]
All good! Happy to contribute!
